/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author a22braisdr
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDEngadirModulo = new javax.swing.JDialog();
        jPanelEngadirModulo = new javax.swing.JPanel();
        lblTituloModulos = new javax.swing.JLabel();
        lblEngadirModulo = new javax.swing.JLabel();
        jPanelOpcionesModulo = new javax.swing.JPanel();
        lblUnidadesModulo = new javax.swing.JLabel();
        jTextFieldNombreModulo = new javax.swing.JTextField();
        lblHorasModulo = new javax.swing.JLabel();
        jTextFieldHorasModulo = new javax.swing.JTextField();
        jTextFieldUnidadesModulo = new javax.swing.JTextField();
        lblNombreModulo = new javax.swing.JLabel();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jDEngadirAlumno = new javax.swing.JDialog();
        jPanelEngadirAlumno = new javax.swing.JPanel();
        lblTituloAlumnos = new javax.swing.JLabel();
        lblEngadirAlumno = new javax.swing.JLabel();
        jPanelOpcionesAlumno = new javax.swing.JPanel();
        jTextFieldNombreAlumno = new javax.swing.JTextField();
        lblLocalidad = new javax.swing.JLabel();
        jTextFieldLocalidad = new javax.swing.JTextField();
        lblNombreModulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnGrabar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListModulos = new javax.swing.JList<>();
        btnGrabarLista = new javax.swing.JButton();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelBotones = new javax.swing.JPanel();
        btnVerAlumno = new javax.swing.JButton();
        btnEngadirAlumno = new javax.swing.JButton();
        btnEngadirModulo = new javax.swing.JButton();
        jMenuOpciones = new javax.swing.JMenuBar();
        jMenuAlumnos = new javax.swing.JMenu();
        jMenuItemEngadirAlumno = new javax.swing.JMenuItem();
        jMenuItemVerAlumno = new javax.swing.JMenuItem();
        jMenuItemGuardarAlumno = new javax.swing.JMenuItem();
        jMenuModulos = new javax.swing.JMenu();
        jMenuItemEngadirModulo = new javax.swing.JMenuItem();
        jMenuItemGuardarModulo = new javax.swing.JMenuItem();

        lblTituloModulos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloModulos.setText("Alta Módulos:");

        lblEngadirModulo.setText("Engadir Módulo");

        lblUnidadesModulo.setText("Unidades:");

        lblHorasModulo.setText("Horas:");

        lblNombreModulo.setText("Nombre:");

        javax.swing.GroupLayout jPanelOpcionesModuloLayout = new javax.swing.GroupLayout(jPanelOpcionesModulo);
        jPanelOpcionesModulo.setLayout(jPanelOpcionesModuloLayout);
        jPanelOpcionesModuloLayout.setHorizontalGroup(
            jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreModulo)
                    .addComponent(lblUnidadesModulo)
                    .addComponent(lblHorasModulo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelOpcionesModuloLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldHorasModulo, jTextFieldNombreModulo, jTextFieldUnidadesModulo});

        jPanelOpcionesModuloLayout.setVerticalGroup(
            jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesModuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreModulo)
                    .addComponent(jTextFieldNombreModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasModulo)
                    .addComponent(jTextFieldHorasModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnidadesModulo)
                    .addComponent(jTextFieldUnidadesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabar.setText("Grabar");

        btnLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jPanelEngadirModuloLayout = new javax.swing.GroupLayout(jPanelEngadirModulo);
        jPanelEngadirModulo.setLayout(jPanelEngadirModuloLayout);
        jPanelEngadirModuloLayout.setHorizontalGroup(
            jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                        .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelOpcionesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEngadirModulo)
                            .addComponent(lblTituloModulos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                        .addComponent(btnGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(83, 83, 83))))
        );
        jPanelEngadirModuloLayout.setVerticalGroup(
            jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirModuloLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTituloModulos)
                .addGap(18, 18, 18)
                .addComponent(lblEngadirModulo)
                .addGap(18, 18, 18)
                .addComponent(jPanelOpcionesModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnLimpiar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDEngadirModuloLayout = new javax.swing.GroupLayout(jDEngadirModulo.getContentPane());
        jDEngadirModulo.getContentPane().setLayout(jDEngadirModuloLayout);
        jDEngadirModuloLayout.setHorizontalGroup(
            jDEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDEngadirModuloLayout.setVerticalGroup(
            jDEngadirModuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lblTituloAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTituloAlumnos.setText("Alta Alumno:");

        lblEngadirAlumno.setText("Engadir Alumno");

        lblLocalidad.setText("Localidad:");

        lblNombreModulo1.setText("Nombre:");

        jLabel1.setText("Módulos:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelOpcionesAlumnoLayout = new javax.swing.GroupLayout(jPanelOpcionesAlumno);
        jPanelOpcionesAlumno.setLayout(jPanelOpcionesAlumnoLayout);
        jPanelOpcionesAlumnoLayout.setHorizontalGroup(
            jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreModulo1)
                            .addComponent(lblLocalidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanelOpcionesAlumnoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldLocalidad, jTextFieldNombreAlumno});

        jPanelOpcionesAlumnoLayout.setVerticalGroup(
            jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcionesAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreModulo1)
                    .addComponent(jTextFieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad)
                    .addComponent(jTextFieldLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelOpcionesAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnGrabar1.setText("Grabar");

        btnLimpiar1.setText("Limpiar");

        jListModulos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListModulos);

        btnGrabarLista.setText("Grabar");

        javax.swing.GroupLayout jPanelEngadirAlumnoLayout = new javax.swing.GroupLayout(jPanelEngadirAlumno);
        jPanelEngadirAlumno.setLayout(jPanelEngadirAlumnoLayout);
        jPanelEngadirAlumnoLayout.setHorizontalGroup(
            jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(btnGrabar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar1)
                        .addGap(74, 74, 74))
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanelOpcionesAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblEngadirAlumno)
                                .addComponent(lblTituloAlumnos)))
                        .addGap(18, 18, 18)
                        .addComponent(btnGrabarLista)
                        .addContainerGap(51, Short.MAX_VALUE))))
        );
        jPanelEngadirAlumnoLayout.setVerticalGroup(
            jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTituloAlumnos)
                .addGap(18, 18, 18)
                .addComponent(lblEngadirAlumno)
                .addGap(18, 18, 18)
                .addComponent(jPanelOpcionesAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanelEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGrabar1)
                            .addComponent(btnLimpiar1))
                        .addGap(43, 43, 43))
                    .addGroup(jPanelEngadirAlumnoLayout.createSequentialGroup()
                        .addComponent(btnGrabarLista)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jDEngadirAlumnoLayout = new javax.swing.GroupLayout(jDEngadirAlumno.getContentPane());
        jDEngadirAlumno.getContentPane().setLayout(jDEngadirAlumnoLayout);
        jDEngadirAlumnoLayout.setHorizontalGroup(
            jDEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDEngadirAlumnoLayout.setVerticalGroup(
            jDEngadirAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEngadirAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AcademiaMas");

        btnVerAlumno.setText("Ver Alumno");

        btnEngadirAlumno.setText("Engadir Alumno");

        btnEngadirModulo.setText("Engadir Módulo");

        javax.swing.GroupLayout jPanelBotonesLayout = new javax.swing.GroupLayout(jPanelBotones);
        jPanelBotones.setLayout(jPanelBotonesLayout);
        jPanelBotonesLayout.setHorizontalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVerAlumno)
                    .addComponent(btnEngadirModulo)
                    .addComponent(btnEngadirAlumno))
                .addContainerGap())
        );

        jPanelBotonesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEngadirAlumno, btnEngadirModulo, btnVerAlumno});

        jPanelBotonesLayout.setVerticalGroup(
            jPanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEngadirAlumno)
                .addGap(18, 18, 18)
                .addComponent(btnEngadirModulo)
                .addGap(18, 18, 18)
                .addComponent(btnVerAlumno)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jMenuAlumnos.setText("Alumnos");

        jMenuItemEngadirAlumno.setText("Engadir Alumno");
        jMenuItemEngadirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEngadirAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumnos.add(jMenuItemEngadirAlumno);

        jMenuItemVerAlumno.setText("Ver Alumno");
        jMenuAlumnos.add(jMenuItemVerAlumno);

        jMenuItemGuardarAlumno.setText("Guardar Alumno");
        jMenuAlumnos.add(jMenuItemGuardarAlumno);

        jMenuOpciones.add(jMenuAlumnos);

        jMenuModulos.setText("Módulos");

        jMenuItemEngadirModulo.setText("Engadir Módulo");
        jMenuModulos.add(jMenuItemEngadirModulo);

        jMenuItemGuardarModulo.setText("Guardar Módulo");
        jMenuModulos.add(jMenuItemGuardarModulo);

        jMenuOpciones.add(jMenuModulos);

        setJMenuBar(jMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemEngadirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEngadirAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEngadirAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEngadirAlumno;
    private javax.swing.JButton btnEngadirModulo;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnGrabar1;
    private javax.swing.JButton btnGrabarLista;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JButton btnVerAlumno;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDEngadirAlumno;
    private javax.swing.JDialog jDEngadirModulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListModulos;
    private javax.swing.JMenu jMenuAlumnos;
    private javax.swing.JMenuItem jMenuItemEngadirAlumno;
    private javax.swing.JMenuItem jMenuItemEngadirModulo;
    private javax.swing.JMenuItem jMenuItemGuardarAlumno;
    private javax.swing.JMenuItem jMenuItemGuardarModulo;
    private javax.swing.JMenuItem jMenuItemVerAlumno;
    private javax.swing.JMenu jMenuModulos;
    private javax.swing.JMenuBar jMenuOpciones;
    private javax.swing.JPanel jPanelBotones;
    private javax.swing.JPanel jPanelEngadirAlumno;
    private javax.swing.JPanel jPanelEngadirModulo;
    private javax.swing.JPanel jPanelOpcionesAlumno;
    private javax.swing.JPanel jPanelOpcionesModulo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldHorasModulo;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldNombreAlumno;
    private javax.swing.JTextField jTextFieldNombreModulo;
    private javax.swing.JTextField jTextFieldUnidadesModulo;
    private javax.swing.JLabel lblEngadirAlumno;
    private javax.swing.JLabel lblEngadirModulo;
    private javax.swing.JLabel lblHorasModulo;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblNombreModulo;
    private javax.swing.JLabel lblNombreModulo1;
    private javax.swing.JLabel lblTituloAlumnos;
    private javax.swing.JLabel lblTituloModulos;
    private javax.swing.JLabel lblUnidadesModulo;
    // End of variables declaration//GEN-END:variables
}
