version: '1'
services:
  jupyterlab:
    image: continuumio/anaconda3:latest
    container_name: anaconda3-jupyterlab
    ports:
      - '8888:8888'
    volumes:
      - ./notebooks:/notebooks
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root"]